name: Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions: {}
jobs:
  eslint:
    name: Code analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun install @microsoft/eslint-formatter-sarif

      - name: Run TypeScript compiler
        run: bunx tsc --noEmit

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: 'true'
        run: bunx eslint
          -f @microsoft/eslint-formatter-sarif
          -o eslint-results.sarif
          .
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Run Prettier
        run: |
          rm eslint-results.sarif
          bunx prettier --check .
