name: Analysis

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  eslint:
    name: Run code & style analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: bunx eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check
