name: Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions: {}
jobs:
  eslint:
    name: Code analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun install @microsoft/eslint-formatter-sarif

      - name: Run TypeScript compiler
        run: bunx tsc --noEmit

      - name: Run ESLint
        run: bunx eslint --format=@microsoft/eslint-formatter-sarif --output-file=eslint-results.sarif --max-warnings=0 .

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v3.30.4
        if: always()
        with:
          sarif_file: eslint-results.sarif

      - name: Run Prettier
        run: bunx prettier --check .
